language: R
sudo: required
dist: trusty

r_binary_packages:
 - rgeos

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libv8-dev
      - libprotobuf-dev # for protolite, a dependency of geojson and thus geojsonio
      - libprotoc-dev
      - protobuf-compiler

notifications:
  email:
    on_success: change
    on_failure: change

