language: R
sudo: required
dist: trusty

r_binary_packages:
 - rgeos

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libv8-dev

notifications:
  email:
    on_success: change
    on_failure: change

