library(cccharts)

#trend_pngs(data = cccharts::air_temperature, ask = FALSE)
# trend_pngs(data = cccharts::degree_days, ask = FALSE)
# # trend_pngs(data = cccharts::flow_station, ask = FALSE)
# trend_pngs(data = cccharts::glacial, ask = FALSE)
trend_pngs(data = cccharts::precipitation, ask = FALSE)
# trend_pngs(data = cccharts::sea_level_station, ask = FALSE)
# trend_pngs(data = cccharts::sea_temperature_station, ask = FALSE)
# trend_pngs(data = cccharts::snow, ask = FALSE)
# trend_pngs(data = cccharts::snow_station, ask = FALSE)
